name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Test
        run: bun test --coverage

      - name: Build
        run: bun run build

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun test --coverage
      - uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          debug: true
